sudo: required
services:
  - docker

before_install:
  - docker build -t mksmanjit/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mksmanjit/react-test npm test 

after_success:
  - docker build -t mksmanjit/complex-client  ./client
  - docker build -t mksmanjit/complex-nginx   ./nginx
  - docker build -t mksmanjit/complex-server  ./server
  - docker build -t mksmanjit/complex-worker  ./worker

  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push mksmanjit/complex-client
  - docker push mksmanjit/complex-nginx
  - docker push mksmanjit/complex-server
  - docker push mksmanjit/complex-worker
